apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging
namePrefix: staging-

patches:
- path: broadcaster-config-patch.yaml
images:
- name: broadcaster
  newName: vienha/broadcaster
  newTag: b516aedf35fcdb683e9f760024c81c1a2eb8fb0b
- name: todo-backend
  newName: vienha/todo-backend
  newTag: b516aedf35fcdb683e9f760024c81c1a2eb8fb0b
