apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging
namePrefix: staging-

patches:
- path: broadcaster-config-patch.yaml
images:
- name: broadcaster
  newName: vienha/broadcaster
  newTag: 7a00410bb4dea72805991516e6fe4060ae5bf772
- name: todo-backend
  newName: vienha/todo-backend
  newTag: 7a00410bb4dea72805991516e6fe4060ae5bf772
