apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging
namePrefix: staging-

patches:
- path: broadcaster-config-patch.yaml
images:
- name: broadcaster
  newName: vienha/broadcaster
  newTag: 017f7e75b1071dad584cc1977a7d90d12af7e2da
- name: todo-backend
  newName: vienha/todo-backend
  newTag: 017f7e75b1071dad584cc1977a7d90d12af7e2da
