apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging
namePrefix: staging-

patches:
- path: broadcaster-config-patch.yaml
images:
- name: broadcaster
  newName: vienha/broadcaster
  newTag: db8b39084eac8ebe6b68984ce84f9f2ab5347adb
- name: todo-backend
  newName: vienha/todo-backend
  newTag: db8b39084eac8ebe6b68984ce84f9f2ab5347adb
