apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging
namePrefix: staging-

patches:
- path: broadcaster-config-patch.yaml
images:
- name: broadcaster
  newName: vienha/broadcaster
  newTag: d89519851e8caa9446ebb6e153a938608e808fba
- name: todo-backend
  newName: vienha/todo-backend
  newTag: d89519851e8caa9446ebb6e153a938608e808fba
