apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: project
spec:
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
