kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummysite-controller-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["stable.dwk"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch", "create", "delete"]
