apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  DB_HOST: postgres.exercises.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: pingpong
  DB_USER: pingpong
